### ISSUE TITLE
ImportError: cannot import name 'invert_warping' from 'skfda._utils'

### ISSUE THREAD

**Issue by jnahlers** [GAA-UAM/scikit-fda#623]
### Bug description summary

I am trying to follow the [example for least squares registration ](https://fda.readthedocs.io/en/stable/modules/preprocessing/autosummary/skfda.preprocessing.registration.LeastSquaresShiftRegistration.html). I am in a fresh conda environment (python=3.10), and have installed scikit-fda from PyPi:
`pip install scikit-fda` (installs scikit-fda-0.9.1).

When I try and import the registration, I get an import error:
`ImportError: cannot import name 'invert_warping' from 'skfda._utils'` 

I have also tried installing the conda version instead, and get the same error. 
`conda install -c conda-forge scikit-fda`

 

### Code to reproduce the bug

```Python
from skfda.preprocessing import registration
```

### Expected result

I would expect it to import 😄 

### Actual result

It doesn't import 😢 

### Traceback (if an exception is raised)

```Python
>>> from skfda.preprocessing import registration
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\username\Anaconda3\envs\test\lib\site-packages\lazy_loader\__init__.py", line 79, in __getattr__
    return importlib.import_module(f"{package_name}.{name}")
  File "C:\Users\username\Anaconda3\envs\test\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\username\Anaconda3\envs\test\lib\site-packages\skfda\preprocessing\registration\__init__.py", line 10, in <module>
    from ..._utils import (
ImportError: cannot import name 'invert_warping' from 'skfda._utils' (C:\Users\username\Anaconda3\envs\test\lib\site-packages\skfda\_utils\__init__.py)
```

### Software versions

scikit-fda version: 0.9.1

**Comment by jnahlers** [comment]
Tested on Windows 10 and Rocky Linux 9.2. Both throw the exception.

**Comment by jnahlers** [comment]
Downgrading python to 3.9 fixed the issue. As scikit-fda `requires-python = ">=3.10"`, I will leave the issue open.

**Comment by jnahlers** [comment]
Some more info: I tried fresh conda envs with `python=3.9`. Using `pip install scikit-fda` I still get the exception coming up, but using `conda install -c conda-forge scikit-fda` the import worked fine.

I would love to hear if this is reproducible, I feel like I might be running into some weird python/conda misconfiguration bug.

**Comment by tomas-ramos21** [comment]
I'm getting a similar error to the one mentioned in this issue when I try to import the library. The code causing it is provided below:

```python
>>> from skfda import FDataGrid
Traceback (most recent call last):
  File "/Users/tomas/Repos/FNNs/model.py", line 3, in <module>
    from skfda import FDataGrid
  File "/Users/tomas/.pyenv/versions/FNNs/lib/python3.9/site-packages/lazy_loader/__init__.py", line 83, in __getattr__
    attr = getattr(submod, name)
  File "/Users/tomas/.pyenv/versions/FNNs/lib/python3.9/site-packages/lazy_loader/__init__.py", line 82, in __getattr__
    submod = importlib.import_module(submod_path)
  File "/Users/tomas/.pyenv/versions/3.9.19/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/tomas/.pyenv/versions/FNNs/lib/python3.9/site-packages/skfda/representation/grid.py", line 33, in <module>
    from .._utils import _check_array_key, _int_to_real, _to_grid_points, constants
ImportError: cannot import name '_check_array_key' from 'skfda._utils' (/Users/tomas/.pyenv/versions/FNNs/lib/python3.9/site-packages/skfda/_utils/__init__.py)
```

I installed `scikit-fda` in a clean environment using Python 3.9.19.

**Comment by tomas-ramos21** [comment]
@jnahlers It seems to be a compatibility issue between `scikit-fda` and the latest version of `scikit-learn`. I was able to import the package by installing an older version (1.4.0) of `scikit-learn`. Like so: `pip install scikit-learn==1.4.0`

**Comment by jnahlers** [comment]
> Note that the current development version only works with Python 3.10 onward. Support for Python 3.9 has been dropped as per [SPEC0](https://scientific-python.org/specs/spec-0000/), which is followed by all major scientific packages. Support for Python 3.10 will be dropped at the end of 2024.

Thanks Carlos! Just a note - the original bug report was for Python 3.10. I also just tried a fresh install on 3.11 and had the same issue (when installing from PyPi). However, when I made *another* fresh 3.11 env and installed the github development version instead, I had no issue.

**Comment by jnahlers** [comment]
I am still getting this error in Python 3.11, but downgrading `scikit-learn` to `scikit-learn==1.4.0` as suggested by @tomas-ramos21 seems to have fixed the issue. Suggest reopening, but I don't have permission to do so.
