### ISSUE TITLE
Failed installation on python 3.11

### ISSUE THREAD

**Issue by daviddavo** [GAA-UAM/scikit-fda#544]
**Describe the bug**
It fails to install on Manjaro with python 3.11 via `pip install scikit-fda`, with the following error:

```
      GPy/kern/src/stationary_cython.c:196:12: fatal error: longintrepr.h: No such file or directory
        196 |   #include "longintrepr.h"
            |            ^~~~~~~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for GPy
  Running setup.py clean for GPy
Failed to build GPy
ERROR: Could not build wheels for GPy, which is required to install pyproject.toml-based projects
```

**Version information**
 - OS: Manjaro
 - Python version: 3.11
 - scikit-fda version: 0.8.1

**Additional context**
It works on Python 3.10

**Comment by vnmabus** [comment]
This comes from an error in one of our dependencies: https://github.com/SheffieldML/GPy/issues/998

**Comment by mrrezaie** [comment]
Hi, I have similar issue in Windows 10, python 3.11. Thank you.

**Comment by vnmabus** [comment]
This is probably solved with https://github.com/jdtuck/fdasrsf_python/issues/32. Please reopen if that is not the case.
